#!/bin/bash
echo "Enter first number"
read a
echo "Enter second number"
read b
echo "addition value is `expr $a + $b`"
echo "addition value is `expr $a - $b`"

echo "addition value is `expr $a \* $b`"
echo "addition value is `expr $a / $b`"
echo "Successful"
